### ISSUE TITLE
Call stack size is being overloaded for very minimal conversions

### ISSUE THREAD

**Issue by saksarip** [tnfe/c2f#3]

**Comment by drawcall** [comment]
Can you describe it in more detail

**Comment by takifouhal** [comment]
I have the same issue ,  

an example that raises the error:

display: flex;
flex-direction: row;
justify-content: center;
align-items: center;
padding: 0px;

position: absolute;
width: 400px;
height: 569px;
left: 466px;
top: 0px;


background: #FFFFFF;

border: 1px solid #E1E3E6;
box-sizing: border-box;
border-radius: 8px;
