### ISSUE TITLE
Not working with percentage property

### ISSUE THREAD

**Issue by zyllus17** [tnfe/c2f#4]
I am using this [site](https://webgradients.com/) to get Gradient colors in CSS. The code puts in a percentage in every color and Flutter throws an error while using the conversion. Can you fix it or tell me the way around it.

Color from Website -
![image](https://user-images.githubusercontent.com/50977126/120097417-f4490200-c14d-11eb-9a42-55a42b2cee47.png)

CSS Code
```css
background-image: linear-gradient(45deg, #ff9a9e 0%, #fad0c4 99%, #fad0c4 100%);
```

Flutter Code generated -

```dart
Container(
  decoration: BoxDecoration(
    gradient: LinearGradient(
      begin: Alignment(0.0, 0.0),
      end: Alignment(0.707, -0.707),
      colors: [Color(0xff9a9e 0%00),Color(0xfad0c4 99%00),Color(0xfad0c4 100%00)],
    ),
  )
),
```

Error -
![image](https://user-images.githubusercontent.com/50977126/120097524-8a7d2800-c14e-11eb-8ffe-f3ca1e18ebfe.png)

Error Message -
```console
Expected to find ','.
Too many positional arguments: 1 expected, but 2 found.
Try removing the extra arguments.
```

**Comment by drawcall** [comment]
Oh, this is a more complicated transition color, I think it needs further processing

**Comment by drawcall** [comment]
fixed please check
