### ISSUE TITLE
text-decoration css property don't convert correctly

### ISSUE THREAD

**Issue by mohagali** [tnfe/c2f#7]
**css input:**
text-decoration: underline;

**Flutter output:**

Container(
  child: Text(
    "Hello World",
    style: TextStyle(
      textDecorationLine: TextDecoration.underline,
      textDecorationStyle: TextDecorationStyle.solid,
      textDecorationColor: Color(0x00000000),
    ),
  ),
),

**error:**

The named parameter 'textDecorationLine' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'textDecorationLine'.dart[undefined_named_parameter](https://dart.dev/diagnostics/undefined_named_parameter)

**flutter version sdk**

sdk: ">=2.16.1 <3.0.0"

**This works for me**

Text(
"Hello World",
style: TextStyle(
decoration: TextDecoration.underline
)

**Comment by drawcall** [comment]
It has been fixed please check
